import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    const { jobId, ideaId, projectId } = await req.json();

    // Fetch idea and project DNA
    const { data: idea, error: ideaError } = await supabase
      .from("ideas")
      .select("*, projects!inner(*)")
      .eq("id", ideaId)
      .single();

    if (ideaError) throw ideaError;

    const brandKit = idea.projects.brand_kit || {};
    
    // Generate script using Lovable AI
    const lovableApiKey = Deno.env.get("LOVABLE_API_KEY");
    
    const systemPrompt = `You are a professional script writer for short-form video content. 
Brand: ${brandKit.name || "Unknown"}
Voice: ${brandKit.voice || "professional, engaging"}
Target Duration: ${idea.target_duration || 60} seconds
Tone: ${idea.tone || "engaging"}

Create a script that:
1. Has a powerful hook (first 3 seconds)
2. Delivers value in 3-5 beats
3. Ends with a clear CTA
4. Matches the brand voice
5. Avoids banned words: ${idea.banned_words?.join(", ") || "none"}`;

    const userPrompt = `Create a script for this video concept:
Title: ${idea.title}
Description: ${idea.description}
Video Concept: ${idea.video_concept || "Not specified"}
Hook Type: ${idea.hook_type || "question"}
Target Platforms: ${idea.target_platforms?.join(", ") || "TikTok"}`;

    const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${lovableApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt }
        ],
        tools: [{
          type: "function",
          function: {
            name: "generate_script",
            description: "Generate a video script with structured format",
            parameters: {
              type: "object",
              properties: {
                hook: { 
                  type: "string", 
                  description: "The opening hook (3-5 seconds)" 
                },
                beats: {
                  type: "array",
                  items: { type: "string" },
                  description: "Array of 3-5 main content beats"
                },
                cta: { 
                  type: "string", 
                  description: "The call-to-action" 
                },
                voice_style: { 
                  type: "string", 
                  description: "Recommended voice style" 
                },
                read_time: {
                  type: "integer",
                  description: "Estimated read time in seconds"
                }
              },
              required: ["hook", "beats", "cta", "voice_style", "read_time"],
              additionalProperties: false
            }
          }
        }],
        tool_choice: { type: "function", function: { name: "generate_script" } }
      })
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      throw new Error(`AI API error: ${aiResponse.status} - ${errorText}`);
    }

    const aiData = await aiResponse.json();
    const toolCall = aiData.choices?.[0]?.message?.tool_calls?.[0];
    
    if (!toolCall) {
      throw new Error("No script generated by AI");
    }

    const scriptData = JSON.parse(toolCall.function.arguments);

    // Create script in database
    const { data: script, error: scriptError } = await supabase
      .from("scripts")
      .insert({
        idea_id: ideaId,
        hook: scriptData.hook,
        beats: scriptData.beats,
        cta: scriptData.cta,
        voice_style: scriptData.voice_style,
        read_time: scriptData.read_time,
        status: "ready",
        quality_scores: { coherence: 0.9, engagement: 0.85 }
      })
      .select()
      .single();

    if (scriptError) throw scriptError;

    // Update idea status
    await supabase
      .from("ideas")
      .update({ status: "script_ready" })
      .eq("id", ideaId);

    // Log completion
    await supabase.from("audit_logs").insert({
      project_id: projectId,
      factory_job_id: jobId,
      action: "script_generated",
      stage: "script",
      details: { ideaId, scriptId: script.id }
    });

    // Update job to completed and advance
    await supabase.functions.invoke("factory-orchestrator", {
      body: { jobId, action: "advance" }
    });

    return new Response(JSON.stringify({ 
      success: true, 
      script 
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" }
    });

  } catch (error) {
    console.error("Script generation error:", error);
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    return new Response(JSON.stringify({ error: errorMessage }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" }
    });
  }
});
